blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Support
    url: https://discord.gg/
    about: "If you need help with the server/plugin or have a question please join the Discord server and ask there."